---
apiVersion: apps/v1
kind: ReplicaSet

metadata:
  name: app
spec:
  selector:
    matchLabels:
      name: app
  replicas: 1
  template:
    metadata:
      name: app
      labels:
        name: app

    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: application
      containers:
      - name: app
        resources:
          requests:
            cpu: 500m
        image: aespinosa/stress
