apiVersion: v1
kind: ReplicationController
metadata:
  name: vegeta
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: vegeta
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: loader
      containers:
      - name: vegeta
        image: aespinosa/vegeta:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 1000m
          limits:
            cpu: 1000m
        command:
          - /vegeta
          - -cpus=1
          - attack
          - -output=/dev/null
          - -targets=/targets.lst
          - -timeout=5s
          - -rate=4000
      dnsPolicy: ClusterFirst
