apiVersion: v1
kind: ReplicationController
metadata:
  name: vegeta
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: vegeta
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: loader
      containers:
      - name: vegeta
        image: aespinosa/vegeta:latest
        resources:
          requests:
            cpu: 500m
        command:
          - /vegeta
          - attack
          - -output=/output.bin
          - -targets=/targets.lst
          - -rate=1000
      dnsPolicy: ClusterFirst
